---
title: "Naive_Bayes.Rmd"
output: html_document
---

```{r }
.libPaths()
install.packages("e1071", dependencies=TRUE,repos='http://cran.us.r-project.org')
install.packages('caret', dependencies = TRUE,repos='http://cran.us.r-project.org' )
.libPaths()

library(e1071)

#1 Suppose you have a database on four customers. You know their income and whether or not they bought your product. Create a data frame with this data.

train_x <- data.frame(buy = c("yes", "no", "no", "yes"),
                      income = c("high", "high", "medium", "low") )
train_x

```

```{r, #2}
#2 Using Bayes rule calculate the probability that a customer will buy your product given that he or she has high income.
#(buy|income=high) = p(income=high|buy) p(buy) / p(income=high) = 1/2 * 1/2 / 1/2 = 0.5


```

```{r,3}
#3 Estimate naive Bayes model using your data above. What is the prior probability of someone buying your product? What is the probability that a customer has a high income give that he or she bought your product?
#The probablity of someone buying your product is 0.5. The probability that a customer has a high income given that they bought my product is 0.5
        
classifier <- naiveBayes(buy~ income, train_x)
classifier

```

```{r,4 }

#4 Using the model you estimated above predict the probability of buying given that a customer has high income. Is your result the same as the one you calculated by hand in question 1? The result is indeed the same


```


```{r,5}
#5 Suppose you have a database on four customers. You know their gender, income and whether or not they bought your product. Create a data frame with this data.

train_y <- data.frame(buy = c("yes", "no", "no", "yes"),
                      income = c("high", "high", "medium", "low"),
                      gender = c("male", "female", "female", "male"))
train_y

```

```{r,6}
#6 Using Bayes rule calculate the probability that a customer will buy your product given that he has high income and male.
#p(income=high,gender=male|buy=yes) * p(buy=yes) / p(income=high,gender=male) =.5 * .5 / 1/4 = 1/4 / 1/4 = 1

```

```{r, 7}
#7 Estimate naive Bayes model using your data above. What is the prior probability of someone buying your product? What is the probability that a customer has a high income given that he or she bought your product? What is the probability that a customer is male given that he bought your product?

classifier_y <- naiveBayes(buy ~ income + gender, train_y)
classifier_y

```

```{r, 8}
#8 Using the model you estimated above, predict the probability of buying given that a customer has a high income and is male. Is your result the same as the one you calculated by hand in question 1?


test <- data.frame(income=c("high"), gender=c("male"))

test

test$income <- factor(test$income, levels=c("high","medium", "low"))

test$gender <- factor(test$gender, levels=c("female","male"))


prediction_y <- predict(classifier_y, test, type = "raw")
prediction_y
#I ended up getting different results

```


