---
title: "predict_citibike.Rmd"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(tidyverse)
library(dplyr)
library(lubridate)

setwd("C:/Users/Peter Farquharson/Documents/coursework/week1")
load("trips.RData")


set.seed(12)
#tripData <- inner_join(trips, weather) #combining trip and weather


#summarizing the data by date and precipitation

tripData_summary <- trips %>% group_by(ymd) %>% summarize(num_trips = n())%>% left_join( weather) %>% mutate(day_of_week = weekdays(ymd)) %>% filter(!is.na(tmin)) 

```

```{r}

#Splitting the sample in 80% for training
train_set <- sample_n(tripData_summary, nrow(tripData_summary) *.8)
test_set <- anti_join(tripData_summary, train_set)

#modeling the regression
Temperature_regression <-lm(formula = num_trips ~ tmax + prcp*tmin + day_of_week +  snwd , train_set)
summary(Temperature_regression)

#predictions for train subset
train_set$predictions <- predict(Temperature_regression, newdata = train_set)

#predictions for test subset
test_set$predictions <- predict(Temperature_regression, newdata = test_set)

#calculating R^2
Rsquared <- cor(test_set$predictions, test_set$num_trips)^2
Rsquared

#calculating RMSE
RMSE<- sqrt(mean((test_set$predictions - test_set$num_trips)^2))
RMSE

#Plots
ggplot(test_set) + geom_line(aes(x = ymd, y = predictions, color = "red")) + geom_point(aes(x = ymd, y = num_trips)) 

ggplot(test_set) +  geom_point(aes(x = predictions, y = num_trips)) 



```