---
title: "Titanic.Rmd"
output: html_document
---

```{r setup, include=FALSE}
install.packages('stargazer', dependencies=TRUE,repos='http://cran.us.r-project.org')
install.packages('caret', dependencies=TRUE,repos='http://cran.us.r-project.org')

library(dplyr)
library(stargazer)
library(caret)
library(modelr)
library(ggplot2)
library(pROC)



titanic_data <- read.csv("titanic_train.csv")
summary(titanic_data)
#1 Let's load the Titanic training data. What are the odds of surviving the shipwreck?

#The chance of surviving is 0.3838 or 38% chance


```

```{r }
#2Using the logit model, estimate how much lower are the odds of survival for men relative to women?

logit <- glm(Survived ~ Sex, data = titanic_data, family = "binomial" )
summary(logit)
exp(coef(logit))
#based on intercept- log_odds is 1.05
#Males have a 92% chance of not surviving relative to women

titanic_data %>% group_by(Sex) %>% summarize(survival = mean(Survived))
model<- titanic_data %>% distinct(Sex)
model
predict(logit, data = model, type = "response")
```

```{r }
#3Controlling for gender, does age have a statistically significant effect on the odds of survival? If so, what is the magnitude of that effect?
logit <- glm(Survived ~ Sex + Age, data = titanic_data, family = "binomial" )
summary(logit)
exp(coef(logit))


#Age has a statistically significant effect because it shows that the younger you are the higher your chance of surviving.
#Magnitude would be approximately 0.1

```

```{r}
#4Controlling for gender, does passenger class have a statistically significant effect on the odds of survival? If so, what is the magnitude of that effect?
logit <- glm(Survived ~ Sex + (Pclass) , data = titanic_data, family = "binomial" )
summary(logit)
exp(coef(logit))
#Passenger class does have a statistically significant effect because the higher the class, the more your chance of survival increases.
#Magnitude is .62

```

```{r}
#5 Controlling for gender, estimate the effect of being in the second class relative to first class, and the effect of being in the third relative to first.

logit <- glm(Survived ~ Sex + as.factor(Pclass) , data = titanic_data, family = "binomial" )
summary(logit)
exp(coef(logit))
#It is more advantageous to be in second class relative to first and better to be in first class relative to third

```

```{r}
#Add fare to the regression you estimated above. Is fare a significant determinant of survival controlling for gender and passenger class? Do you think that if we regressed survival on just gender and fare, fare would be significant? Explain.

logit <- glm(Survived ~ Sex + as.factor(Pclass) + Fare , data = titanic_data, family = "binomial" )
summary(logit)
exp(coef(logit))



```

```{r }
#As we know from the movie, Jack traveled in the third class and paid 5 pounds (I know that Jack actually won the ticket in poker, but Swen, from whom Jack won the ticket, paid .). Rose traveled in the first class and paid 500 for her ticket (I know that her fiancee, Cal Hockley - Pittsburgh steel tycoon, actually bought the ticket, but .). What is the probability that Jack will survive? What is the probability that Rose will survive?

logit <- glm(Survived ~ Sex + as.factor(Pclass) + Fare , data = titanic_data, family = "binomial" )
summary(logit)
exp(coef(logit))

predictor<- data.frame(Pclass = factor(c(1,3),levels=c(1,2,3)),
                       Sex = factor(c("male","female")), 
                                    Fare = c(5,500))
predictor$datapredict <- predict(logit, predictor, type = "response")
predictor



```


```{r}
#Create your own logistic model and make predictions for passengers in the Titanic test data set. Keep in mind that you must make predictions for all passengers in the test data (even those with missing values). Use your own probability cut off for predicting survival (0.5 is a natural start). Did you do better with logistic regression than with decision trees? Which algorithm do you like better?

logit <- glm(Survived ~  PassengerId + as.factor(Pclass)  , data = titanic_data, family = "binomial" )
summary(logit)
exp(coef(logit))

titanic_data %>% filter(!is.na(Name)) %>% group_by(Name, PassengerId) %>%summarize(survival = mean(Survived)) %>% View()
model1<-titanic_data
model1$pred <- predict(logit, model1, type = "response")
#ggplot(model1, aes(x = PassengerId, y = survival)) + geom_line()
# plot_data$pred <- predict(logit, plot_data, type = "response")
ggplot(model1, aes(x =PassengerId , y = pred)) + geom_point() + geom_smooth()
# ggplot(plot_data, aes(x = Sex, y = pred, color = Age)) + geom_line() + geom_point(aes(x = Sex, y = frac))

#Testing
set.seed(364)
sample <- sample(nrow(titanic_data), floor(nrow(titanic_data)*0.5))

train <- titanic_data[sample,]
test<- titanic_data[sample,]

logit <- glm(Survived ~  PassengerId + as.factor(Pclass)  , data = titanic_data, family = "binomial" )

test$pred <- predict(logit,test,type = "response")
test$survived_pred <- ifelse(test$pred > 0.5, "1", "0")

confusionMatrix(factor(test$survived_pred), factor(test$Survived))

roc <- roc(as.numeric(test$Survived), as.numeric(test$survived_pred))
roc

plot.roc(roc)


```
```



